repo_id: "bag_recorded_dataset"
robot_type: "Franka"
resume: false
fps: 30
num_episodes: 3
push_to_hub: false

# System configuration
use_sound: true
queue_size: 16
writer_timeout: 10.0

# Bag recording configuration
use_bag_recording: true
bag_output_path: "/tmp/crisp_bags"
bag_compression: "zstd"
