leader:
  robot_type: franka

leader_gripper:
  from_yaml: trigger_left.yaml

gravity_compensation_controller: control/gravity_compensation.yaml

leader_namespace: left
leader_gripper_namespace: left/trigger

use_gripper: true
disable_gripper_torque: true
